##############################################################################################################################
#                                          Deploying DynamoDB Table
##############################################################################################################################

#DynamoDB table to store the faceprints generated by Rekognition service 

resource "aws_dynamodb_table" "faceprints-table" {
  name = "face-prints-table"
  hash_key = "RekognitionId"
  billing_mode = "PAY_PER_REQUEST"

  attribute {
    type = "S"
    name = "RekognitionId"
  }
  tags = {
    Name = "face-prints-table"
    Environment = "PROD"
  }
}